import { Product, CartItem } from "@/lib";

export const exampleProducts: Product[] = [
  {
    id: 1,
    name: "Iced Americano",
    price: 4.5,
    category: "Coffee",
    image: "/mock/images/americano.png",
    color: "#78350f",
  },
  {
    id: 2,
    name: "Cappuccino",
    price: 5.0,
    category: "Coffee",
    image: "/mock/images/cappuccino.png",
    color: "#d97706",
  },
  {
    id: 3,
    name: "Latte",
    price: 5.25,
    category: "Coffee",
    image: "/mock/images/latte.png",
    color: "#b45309",
  },
  {
    id: 4,
    name: "Espresso",
    price: 3.5,
    category: "Coffee",
    image: "/mock/images/espresso.png",
    color: "#451a03",
  },
  {
    id: 5,
    name: "Mocha",
    price: 5.5,
    category: "Coffee",
    image: "/mock/images/mocha.png",
    color: "#92400e",
  },
  {
    id: 6,
    name: "Caramel Macchiato",
    price: 5.75,
    category: "Coffee",
    image: "/mock/images/caramel_macchiato.png",
    color: "#d97706",
  },
  {
    id: 7,
    name: "Matcha Latte",
    price: 5.5,
    category: "Tea",
    image: "/mock/images/matcha_latte.png",
    color: "#166534",
  },
  {
    id: 8,
    name: "Croissant",
    price: 3.75,
    category: "Bakery",
    image: "/mock/images/croissant.png",
    color: "#f59e0b",
  },
  {
    id: 9,
    name: "Blueberry Muffin",
    price: 4.0,
    category: "Bakery",
    image: "/mock/images/blueberry_muffin.png",
    color: "#6366f1",
  },
  {
    id: 10,
    name: "Cheesecake",
    price: 6.5,
    category: "Dessert",
    image: "/mock/images/cheesecake.png",
    color: "#eab308",
  },
  {
    id: 11,
    name: "Chocolate Cake",
    price: 6.0,
    category: "Dessert",
    image: "/mock/images/chocolate_cake.png",
    color: "#3f3f46",
  },
  {
    id: 12,
    name: "Iced Tea",
    price: 3.5,
    category: "Tea",
    image: "/mock/images/iced_tea.png",
    color: "#ef4444",
  },
];

export const exampleCartItems: CartItem[] = [
  { ...exampleProducts[0], quantity: 2 },
  { ...exampleProducts[7], quantity: 1 },
  { ...exampleProducts[4], quantity: 3 },
];
