import { AppSettings } from "@/lib";

export const THEME_PRESETS = {
  compact: {
    theme_preset: "compact" as const,
    sidebar_scale: 85,
    cart_scale: 90,
    grid_scale: 90,
    button_scale: 85,
    display_scale: 90,
    theme_radius: 0.4,
  },
  cozy: {
    theme_preset: "cozy" as const,
    sidebar_scale: 100,
    cart_scale: 100,
    grid_scale: 100,
    button_scale: 100,
    display_scale: 100,
    theme_radius: 0.8,
  },
};

export const DEFAULT_SETTINGS: AppSettings = {
  currency_symbol: "$",
  tax_enabled: true,
  tax_rate: 7.0,
  display_scale: 100.0,
  sidebar_scale: 100.0,
  cart_scale: 100.0,
  grid_scale: 100.0,
  manage_table_scale: 100.0,
  stock_table_scale: 100.0,
  material_table_scale: 100.0,
  category_table_scale: 100.0,
  sidebar_font_scale: 100.0,
  cart_font_scale: 100.0,
  grid_font_scale: 100.0,
  manage_table_font_scale: 100.0,
  stock_table_font_scale: 100.0,
  material_table_font_scale: 100.0,
  category_table_font_scale: 100.0,
  setting_page_scale: 100.0,
  setting_page_font_scale: 100.0,
  header_font_scale: 100.0,
  button_scale: 100.0,
  button_font_scale: 100.0,
  layout_max_width: 1280.0,
  payment_modal_scale: 100.0,
  payment_modal_font_scale: 100.0,
  history_font_scale: 100.0,
  payment_numpad_height: 320,
  numpad_scale: 100,
  numpad_font_scale: 100,
  numpad_display_font_scale: 100,
  numpad_button_height: 80,
  numpad_gap: 12,
  cart_item_font_size: 100,
  cart_item_header_font_size: 100,
  cart_item_price_font_size: 100,
  cart_item_padding: 10,
  cart_item_margin: 8,
  // ── Product Grid Tuning ──
  grid_item_padding: 16,
  grid_item_radius: 24,
  grid_item_title_font_size: 100,
  grid_item_price_font_size: 100,
  grid_gap: 20,
  // ── Typography ──
  typography_font_family: null,
  typography_base_size: null,
  typography_heading_weight: null,
  typography_body_weight: null,
  typography_line_height: null,
  typography_letter_spacing: null,
  image_storage_path: null,
  db_storage_path: null,
  theme_primary_color: null,
  theme_radius: 0.5,
  theme_preset: "cozy",
};
